### ISSUE TITLE
关于论文中表3的指标计算

### ISSUE THREAD

**Issue by nth2000** [ChartMimic/ChartMimic#2]
感谢您的精彩工作！
![图片](https://github.com/ChartMimic/ChartMimic/assets/82802716/d72c3936-78bb-40fe-9844-3ba21dca0f49)
我在执行如图所示的步骤3，只会得到每个文件的Text Layout Type Color值 
那么请问论文中表3的指标是如何计算出来的呢？
非常感谢！

**Comment by yc1999** [comment]
Thanks for your kind attention~ We apologize for the late reply.
You can check [direct_mimic/get_results.ipynb](https://github.com/ChartMimic/ChartMimic/blob/main/scripts/direct_mimic/get_results.ipynb) and [customized_mimic/get_results.ipynb](https://github.com/ChartMimic/ChartMimic/blob/main/scripts/customized_mimic/get_results.ipynb) for more information.
