### ISSUE TITLE
I cannot find the details of the submission guideline.

### ISSUE THREAD

**Issue by zhimin-z** [ChartMimic/ChartMimic#3]
![image](https://github.com/user-attachments/assets/e143b3fc-aeb0-4bc2-a802-3a25aa4287c4)
Check the linkage but found there is no submission guideline available in the GitHub README..

**Comment by ChartMimic** [comment]
You can contribute your results via a pull request at https://github.com/ChartMimic/ChartMimic.github.io, or alternatively, you can send your results directly to our email. Thank you for your interest.

**Comment by zhimin-z** [comment]
> You can contribute your results via a pull request at https://github.com/ChartMimic/ChartMimic.github.io, or alternatively, you can send your results directly to our email. Thank you for your interest.

Thanks for your clarification. Would you like to add this guideline into the documentation?
