### ISSUE TITLE
Test bugs in the code

### ISSUE THREAD

**Issue by xxlllz** [ChartMimic/ChartMimic#4]
I found there are problems in the evaluation when you evaluate with gpt4, the conversation you defined as follows,
```
    def _constract_conversation(self, orginal_png_file, generated_png_file):
        conversation = [
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": self.instruction},
                    {"type": "image", "image_url": generated_png_file},
                    {"type": "image", "image_url": orginal_png_file},
                ],
            }
        ]
        return conversation
```
However, in your prompt, you treat the first figure as the ground truth figure and the latter as the generated file. This error leads to using the ground truth figure to compare with the generated figure, which influences the final score

**Comment by ChartMimic** [comment]
Thank you for your feedback, and we apologize for missing the update to this older version of the code. Over the past month, we’ve made updates to the ChartMimic dataset and code, and we will re-upload the corrected version soon. Thank you for your attention to this. By the way, interestingly, we previously checked the results and found that the difference was not significant.

**Comment by xxlllz** [comment]
Yes, I have tested the wrong version and the correct version, the difference is just about 3-5 points on gpt4 evaluation. By the way, when would you upload the latest version, we want to evaluate our model on this dataset. Thank you in advance.
