### ISSUE TITLE
Performance difference

### ISSUE THREAD

**Issue by CleyLyChen** [ChartMimic/ChartMimic#6]
Hi, Great work!
I tried to test the Phi3-vision model on custom mimic task, but the low-level performance is different from your paper. The gap is nearly 10 points, Here is my result:
Text : 26.85 while it is 30.9 in paper
Layout : 40.35 while it is 52.5 in paper 
Type : 40.97 while it is 46.6 in paper 
Color : 25.57 while it is 42.0 in paper
Avg : 33.44 while it is 43.0 in paper
I don't know what causes this problem.
Do you have any suggestions to help me reproduce the similar performance? 
Looking forward to your reply!

**Comment by MiaSanLei** [comment]
> Hi, Great work! I tried to test the Phi3-vision model on custom mimic task, but the low-level performance is different from your paper. The gap is nearly 10 points, Here is my result: Text : 26.85 while it is 30.9 in paper Layout : 40.35 while it is 52.5 in paper Type : 40.97 while it is 46.6 in paper Color : 25.57 while it is 42.0 in paper Avg : 33.44 while it is 43.0 in paper I don't know what causes this problem. Do you have any suggestions to help me reproduce the similar performance? Looking forward to your reply!

Hello, I met the same problem, how did you solve it?
