### ISSUE TITLE
Generated Code Runtime Error Case

### ISSUE THREAD

**Issue by BX126** [ChartMimic/ChartMimic#7]
Hello,

Thank you for sharing this interesting work!

I noticed that the implemented code detects runtime errors in the generated code within `ChartMimic/chart2code/utils/post_process/code_interpreter.py`. It seems like that if an error occurs in the generated code, it will be treated as a blank image by generating an empty figure. Is my understanding correct? Additionally, does Table 3 in the paper exclude all such cases (generated code has runtime error)?

**Comment by yc1999** [comment]
Thanks for your interest.

> It seems like that if an error occurs in the generated code, it will be treated as a blank image by generating an empty figure. Is my understanding correct?

Yes, if an error occurs, it will be treated as a blank image.

>  Additionally, does Table 3 in the paper exclude all such cases (generated code has runtime error)?

We do not exclude all such cases. If the code fails to execute, all scores for this example will be zero.
